apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: postgres-2
  namespace: crossplane-and-servicebindings-2
spec:
  providerConfigRef:
     name: helm-provider
  forProvider: # maps to the parameters of the external resource
    chart:
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 16.7.20
    namespace: crossplane-and-servicebindings-2
    values:
      primary:
        persistence:
          size: 1Gi
        pgHbaConfiguration: |-
          local all all trust
          host all all localhost trust
          host inclusion default 0.0.0.0/0 password
      global:
        postgresql:
          auth:
            username: default
            database: inclusion
  connectionDetails: # Define connection details
  - apiVersion: v1
    kind: Service
    name: postgres-2-postgresql
    namespace: crossplane-and-servicebindings-2
    fieldPath: spec.clusterIP
    toConnectionSecretKey: host
  - apiVersion: v1
    kind: Service
    name: postgres-2-postgresql
    namespace: crossplane-and-servicebindings-2
    fieldPath: spec.ports[0].port
    toConnectionSecretKey: port
  - apiVersion: v1
    kind: Secret
    name: postgres-2-postgresql
    namespace: crossplane-and-servicebindings-2
    fieldPath: data.password
    toConnectionSecretKey: password
  - apiVersion: apps/v1
    kind: StatefulSet
    name: postgres-2-postgresql
    namespace: crossplane-and-servicebindings-2
    fieldPath: spec.template.spec.containers[0].env[4].value
    toConnectionSecretKey: username
  - apiVersion: apps/v1
    kind: StatefulSet
    name: postgres-2-postgresql
    namespace: crossplane-and-servicebindings-2
    fieldPath: spec.template.spec.containers[0].env[7].value
    toConnectionSecretKey: database
  writeConnectionSecretToRef: # Provider saves connection details in the Kubernetes secret
    name: postgres-connection-secrets
    namespace: crossplane-and-servicebindings-2
