apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cnr-inclusion
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "3"
    spec:
      containers:
      - image: $INCLUSION_CONTAINER_IMAGE
        name: user-container
        env: 
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: csb-postgres-2-connection-secrets
              key: username
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: csb-postgres-2-connection-secrets
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: csb-postgres-2-connection-secrets
              key: port
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: csb-postgres-2-connection-secrets
              key: database
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: csb-postgres-2-connection-secrets
              key: password