apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: csb-postgres-2
spec:
  forProvider:
    chart:
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 13.0.0
    namespace: $DEMO_NS
    values:
      primary:
        persistence:
          size: 1Gi
        pgHbaConfiguration: |-
          local all all trust
          host all all localhost trust
          host inclusion default 0.0.0.0/0 password
      global:
        postgresql:
          auth:
            username: default
            database: inclusion
  connectionDetails:
  - apiVersion: v1
    kind: Service
    name: csb-postgres-2-postgresql
    namespace: $DEMO_NS
    fieldPath: spec.clusterIP
    toConnectionSecretKey: host
  - apiVersion: v1
    kind: Service
    name: csb-postgres-2-postgresql
    namespace: $DEMO_NS
    fieldPath: spec.ports[0].port
    toConnectionSecretKey: port
  - apiVersion: v1
    kind: Secret
    name: csb-postgres-2-postgresql
    namespace: $DEMO_NS
    fieldPath: data.password
    toConnectionSecretKey: password
  - apiVersion: apps/v1
    kind: StatefulSet
    name: csb-postgres-2-postgresql
    namespace: $DEMO_NS
    fieldPath: spec.template.spec.containers[0].env[4].value
    toConnectionSecretKey: username
  - apiVersion: apps/v1
    kind: StatefulSet
    name: csb-postgres-2-postgresql
    namespace: $DEMO_NS
    fieldPath: spec.template.spec.containers[0].env[7].value
    toConnectionSecretKey: database
  writeConnectionSecretToRef:
    name: csb-postgres-2-connection-secrets
    namespace: $DEMO_NS
