apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: inclusion-db
  namespace: crossplane-and-servicebindings-4
spec:
  service:
    apiVersion: v1
    kind: Secret
    name: postgres-connection-secrets
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: inclusion