apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: cnr-inclusion-db
spec:
  service:
    apiVersion: v1
    kind: Secret
    name: cnr-postgres-connection-secrets
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: cnr-inclusion