apiVersion: timosalm.de/v1alpha1
kind: xPostgreSQLDatabase
metadata:
  name: csb-postgres
  labels: 
    crossplane.io/claim-namespace: $DEMO_NS
spec:
  storage: 2
  writeConnectionSecretToRef:
    name: csb-postgres-connection-secrets
    namespace: $DEMO_NS