apiVersion: timosalm.de/v1alpha1
kind: PostgreSQLDatabase
metadata:
  name: postgres
  namespace: crossplane-and-servicebindings-3
spec:
  storage: 2
  writeConnectionSecretToRef:
    name: postgres-connection-secrets