apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqldatabases.timosalm.de
spec:
  group: timosalm.de
  names:
    kind: xPostgreSQLDatabase
    plural: xpostgresqldatabases
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              storage:
                default: 1
                description: The storage capacity of the database in gigabytes
                type: integer
    served: true
    referenceable: true
  connectionSecretKeys:
  - host
  - port
  - database
  - username
  - password
  claimNames:
    kind: PostgreSQLDatabase
    plural: postgresqldatabases