apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xpostgresqldatabases.timosalm.de
spec:
  group: timosalm.de
  names:
    kind: xPostgreSQLDatabase
    plural: xpostgresqldatabases
  versions: 
  # The schema of each version can’t change any existing fields. 
  # Breaking schema changes between versions requires the use of conversion webhooks
  # Crossplane recommends implementing breaking schema changes as brand new XRDs.
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              storage:
                default: 1
                description: The storage capacity of the database in gigabytes
                type: integer
    served: true
    referenceable: true
  connectionSecretKeys: # Limits what's provided to a composite resource or Claim
  - host
  - port
  - database
  - username
  - password
  claimNames:
    kind: PostgreSQLDatabase
    plural: postgresqldatabases