apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: cnr-inclusion-db
spec:
  service:
    apiVersion: timosalm.de/v1alpha1
    kind: PostgreSQLDatabase
    name: cnr-postgres
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: cnr-inclusion