apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: inclusion-db
  namespace: crossplane-and-servicebindings-5
spec:
  service:
    apiVersion: timosalm.de/v3
    kind: PostgreSQLDatabase
    name: postgres
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: inclusion