apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresqldatabases-service-bindings
  labels:
    servicebinding.io/controller: "true" # matches the aggregation rule selector
rules:
- apiGroups:
  - timosalm.de
  resources:
  - postgresqldatabases
  verbs:
  - get
  - list
  - watch